# Generated by Django 5.1.1 on 2024-10-11 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Titular'), (1, 'Reserva'), (2, 'Vazio')], default=2),
        ),
        migrations.RenameField(
            model_name='match',
            old_name='acrescimo',
            new_name='add',
        ),
        migrations.RemoveField(
            model_name='match',
            name='horario_pertida',
        ),
        migrations.AddField(
            model_name='match',
            name='time_match',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player_match',
            name='player_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
