# Generated by Django 5.1.1 on 2024-10-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_point_player_alter_point_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match',
            name='time_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team_match'),
        ),
    ]
