# Generated by Django 5.1.1 on 2024-10-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_player_match_time_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_match',
            old_name='time_match',
            new_name='team_match',
        ),
    ]
