# Generated by Django 5.1.1 on 2024-10-24 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_time_match_player_match_team_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalties',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penalties',
            name='type_penalties',
            field=models.IntegerField(choices=[(0, 'Cartão Vermelho'), (1, 'Cartão Amarelo'), (2, 'lack'), (3, 'Nenhum')], default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/logoifs-teste.png', upload_to='photo_player/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='hexcolor',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
