# Generated by Django 5.1.1 on 2024-10-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_penalties_player_alter_penalties_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
    ]
