# Generated by Django 5.1.1 on 2024-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_assistance_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_pause',
            name='end_pause',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
