# Generated by Django 5.1.1 on 2024-11-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sport_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volley_match',
            old_name='sets_team',
            new_name='sets_team_a',
        ),
        migrations.RemoveField(
            model_name='volley_match',
            name='team_match',
        ),
        migrations.AddField(
            model_name='volley_match',
            name='sets_team_b',
            field=models.IntegerField(default=0),
        ),
    ]
