# Generated by Django 5.1.1 on 2024-11-26 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_sets_team_volley_match_sets_team_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_config/')),
                ('status', models.IntegerField(choices=[(0, 'Em uso'), (1, 'Nenhum')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('qrcode', models.ImageField(blank=True, default='defaults/qrcode.png', null=True, upload_to='photos_config/')),
                ('areasup', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='logs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em breve'), (1, 'Acontecendo'), (2, 'Finalizada'), (3, 'Cancelada'), (4, 'Pausada'), (5, 'Nenhum')], default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='volley_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.volley_match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/person.png', upload_to='photo_player/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/team.png', upload_to='logo_team/'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('datetime', models.TimeField(auto_now_add=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match')),
            ],
        ),
    ]
