# Generated by Django 5.1.3 on 2025-01-31 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_banner_config_sport_logs_alter_match_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('siape', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, default='defaults/person.png', upload_to='photo_technician/')),
                ('sexo', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Nenhum')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
