# Generated by Django 5.1.1 on 2025-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, 'Corrida'), (7, 'Salto em altura'), (8, 'Queimado')]),
        ),
        migrations.AlterField(
            model_name='team_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, 'Corrida'), (7, 'Salto em altura'), (8, 'Queimado')]),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
