# Generated by Django 5.1.3 on 2025-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_player_admin_player_campus_player_date_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='campus',
            field=models.IntegerField(choices=[(0, 'Lagarto'), (1, 'Aracaju'), (2, 'Socorro'), (3, 'Poço Redondo'), (4, 'São Cristovão'), (5, 'Itabaiana'), (6, 'Glória'), (7, 'Estância'), (8, 'Propriá'), (9, 'Tobias Barreto'), (10, 'Reitoria')], default=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, 'Corrida 100 M'), (7, 'Salto em distância'), (8, 'Queimado')]),
        ),
        migrations.AlterField(
            model_name='team_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, 'Corrida 100 M'), (7, 'Salto em distância'), (8, 'Queimado')]),
        ),
    ]
