# Generated by Django 5.1.3 on 2025-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_player_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bulletin',
            field=models.FileField(default=1, upload_to='bulletins/'),
            preserve_default=False,
        ),
    ]
