# Generated by Django 5.1.3 on 2025-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_team_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
