# Generated by Django 5.1.3 on 2025-02-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_player_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Lançamento de peso')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='campus',
            field=models.IntegerField(choices=[(0, 'Aracaju'), (1, 'Estância'), (2, 'Glória'), (3, 'Itabaiana'), (4, 'Lagarto'), (5, 'Poço Redondo'), (6, 'Propriá'), (7, 'São Cristovão'), (8, 'Socorro'), (9, 'Tobias Barreto'), (10, 'Reitoria')], default=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='campus',
            field=models.IntegerField(choices=[(0, 'Aracaju'), (1, 'Estância'), (2, 'Glória'), (3, 'Itabaiana'), (4, 'Lagarto'), (5, 'Poço Redondo'), (6, 'Propriá'), (7, 'São Cristovão'), (8, 'Socorro'), (9, 'Tobias Barreto'), (10, 'Reitoria')], default=10),
        ),
        migrations.AlterField(
            model_name='team_sport',
            name='sport',
            field=models.IntegerField(choices=[(0, 'Futsal'), (1, 'Voleibol'), (2, 'Voleibol sentado'), (3, 'Handebol'), (4, 'Xadrez'), (5, 'Tênis de mesa'), (6, '100 M'), (7, 'Salto em distância'), (8, 'Lançamento de dardo'), (9, 'Lançamento de peso')]),
        ),
        migrations.AlterField(
            model_name='technician',
            name='campus',
            field=models.IntegerField(choices=[(0, 'Aracaju'), (1, 'Estância'), (2, 'Glória'), (3, 'Itabaiana'), (4, 'Lagarto'), (5, 'Poço Redondo'), (6, 'Propriá'), (7, 'São Cristovão'), (8, 'Socorro'), (9, 'Tobias Barreto'), (10, 'Reitoria')], default=10),
        ),
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='defaults/person.png', upload_to='photo_voluntary/')),
                ('campus', models.IntegerField(choices=[(0, 'Aracaju'), (1, 'Estância'), (2, 'Glória'), (3, 'Itabaiana'), (4, 'Lagarto'), (5, 'Poço Redondo'), (6, 'Propriá'), (7, 'São Cristovão'), (8, 'Socorro'), (9, 'Tobias Barreto'), (10, 'Reitoria')], default=10)),
                ('registration', models.CharField(default='00000000000', max_length=11)),
                ('type_voluntary', models.IntegerField(choices=[(0, 'Voluntario'), (1, 'Organização'), (3, 'Técnico')], default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
